# Request GPU on CANFAR
# curl -E .ssl/cadcproxy.pem 'https://ws-uv.canfar.net/skaha/v0/session?name=dwarforge-gpu&cores=16&ram=64&gpus=1' -d "image=images.canfar.net/skaha/astroml-gpu-vscode:latest&type=contributed"


# Base directory containing all tile subdirectories
base_dir: "/arc/projects/unions/ssl/data/raw/tiles/dwarforge"

# List of model checkpoint paths
model_paths:
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_0/best_model-epoch=07-valid_loss=0.0312.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_1/best_model-epoch=39-valid_loss=0.0322.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_2/best_model-epoch=14-valid_loss=0.0378.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_3/best_model-epoch=75-valid_loss=0.0292.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_4/best_model-epoch=14-valid_loss=0.0272.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_5/best_model-epoch=19-valid_loss=0.0244.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_6/best_model-epoch=33-valid_loss=0.0425.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_7/best_model-epoch=21-valid_loss=0.0315.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_8/best_model-epoch=45-valid_loss=0.0265.ckpt"
  - "/arc/home/heestersnick/dwarforge/models/kfold/fold_9/best_model-epoch=41-valid_loss=0.0266.ckpt"

# Processing mode: "cpu" or "gpu"
processing_mode: "gpu"

# CPU mode settings
cpu:
  # Number of worker processes to use
  # If null, will use CPU count - 1
  num_workers: 15
  
  # Batch size for inference
  batch_size: 64
  
  # Batch size for preprocessing (to manage memory)
  process_batch_size: 150

# GPU mode settings
gpu:
  # Number of CPU processes for preprocessing
  preprocessing_workers: 4
  
  # Number of CPU processes for writing results
  writer_workers: 2
  
  # Batch size for GPU inference (typically larger than CPU)
  batch_size: 128
  
  # Batch size for preprocessing
  process_batch_size: 150
  
  # Size of communication queues
  queue_size: 50

# Logging configuration
log_dir: "./logs"
log_name: "inference"
log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# Set to true to resume processing from failed_tiles.txt
resume: false

# Test mode - set to true to run on only {test_size} tiles and save results to a test directory
# without overwriting the original tiles
test_mode: false
# Number of tiles to process in test mode
test_size: 10
# Directory to save test results
test_dir: "./test_results"